### ISSUE TITLE
Running update_data.py fails

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binder-data#10]
With

```
15:41 $ python3 billing/update_data.py 
Updating data...
Traceback (most recent call last):
  File "billing/update_data.py", line 60, in <module>
    download_data()
  File "billing/update_data.py", line 17, in download_data
    proc_data = pd.read_json('./data/proc/data.json', orient='split')
  File "/home/yuvipanda/.local/share/virtualenvs/binder-data-fDgQ-NJZ/lib/python3.6/site-packages/pandas/io/json/json.py", line 422, in read_json
    result = json_reader.read()
  File "/home/yuvipanda/.local/share/virtualenvs/binder-data-fDgQ-NJZ/lib/python3.6/site-packages/pandas/io/json/json.py", line 529, in read
    obj = self._get_object_parser(self.data)
  File "/home/yuvipanda/.local/share/virtualenvs/binder-data-fDgQ-NJZ/lib/python3.6/site-packages/pandas/io/json/json.py", line 546, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/yuvipanda/.local/share/virtualenvs/binder-data-fDgQ-NJZ/lib/python3.6/site-packages/pandas/io/json/json.py", line 638, in parse
    self._parse_no_numpy()
  File "/home/yuvipanda/.local/share/virtualenvs/binder-data-fDgQ-NJZ/lib/python3.6/site-packages/pandas/io/json/json.py", line 856, in _parse_no_numpy
    loads(json, precise_float=self.precise_float))}
ValueError: Expected object or value
```

**Comment by choldgraf** [comment]
ugh - yep it's broken for me too, maybe something in the API changed?

**Comment by betatim** [comment]
Close after today's update?

**Comment by choldgraf** [comment]
well.....it worked for me two days ago :-)  can you give it a shot and see if it works w/ the new instructions?
